name: milkton_executive
description: Milkton Executive App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.6.0+46

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_remote_config: ^0.10.0+2
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: "^1.3.0"
  # State Management
  get: ^4.1.4
  # GraphQL Client
  graphql_flutter: ^5.0.0-nullsafety.5
  # Http Requests
  http: ^0.13.3
  # Splash Screen Animation
  lottie: ^1.0.1
  # Device Storage
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
