name: build

on:
  push
  
env:
  ANDROID_SERVICE: ${{secrets.ANDROID_SERVICE}}
  STORE_PASSWORD: ${{secrets.STORE_PASSWORD}}
  SIGNING_KEY: ${{secrets.SIGNING_KEY}}
  KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
  KEY_ALIAS: ${{secrets.KEY_ALIAS}}

jobs:
  flutter-build:
    name: Run flutter build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: milkton_executive
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Configure Service account, Keystore and Signing Config
        run: |
          echo "$ANDROID_SERVICE" | base64 --decode > android/app/google-services.json
          echo "$SIGNING_KEY" | base64 --decode > android/app/key.jks
          echo "storeFile=key.jks" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storePassword=$STORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
      - name: Build App
        run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: milkton_executive/build/app/outputs/flutter-apk/app-release.apk
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: release-apk
      - name: Display structure of downloaded files
        run: ls -R
