name: build-test

on:
  push
  
env:
  API_SECRETS: ${{secrets.API_SECRETS}}

jobs:
  flutter-build:
    name: Run flutter build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: milkton_executive
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Add API SECRETs
        run: |
          touch lib/configs/apiSecrets.dart
          echo $API_SECRETS >> lib/configs/apiSecrets.dart
          cat lib/configs/apiSecrets.dart
      - name: Build App
        run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --no-codesign
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: milkton_executive/build/app/outputs/flutter-apk/app-release.apk
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: release-apk
      - name: Display structure of downloaded files
        run: ls -R
